#Keyword selection
Keyword:
    owner: 'owner, made this'
    twitter: 'twitter'
Owner: CreeperKraft 
#This is for owner information
Website: www.creeperkraftservers.com
#Your website information
Facebook: facebook.com/creeperkraftservers
#Your facebook information
Twitter: twitter.com/creeperkraft
#Your twitter information
Member: Go to creeperkraft.com for membership information
#Your membership information